package com.libertador.pojos;
// Generated Jul 15, 2015 12:03:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int dni;
     private String nombre;
     private String apellido;
     private Set recibos = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(int dni) {
        this.dni = dni;
    }
    public Alumno(int dni, String nombre, String apellido, Set recibos) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellido = apellido;
       this.recibos = recibos;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Set getRecibos() {
        return this.recibos;
    }
    
    public void setRecibos(Set recibos) {
        this.recibos = recibos;
    }




}


