package com.libertador.pojos;
// Generated Jul 15, 2015 12:03:05 AM by Hibernate Tools 4.3.1



/**
 * Recibo generated by hbm2java
 */
public class Recibo  implements java.io.Serializable {


     private Integer cod;
     private Alumno alumno;
     private Integer monto;

    public Recibo() {
    }

	
    public Recibo(Alumno alumno) {
        this.alumno = alumno;
    }
    public Recibo(Alumno alumno, Integer monto) {
       this.alumno = alumno;
       this.monto = monto;
    }
   
    public Integer getCod() {
        return this.cod;
    }
    
    public void setCod(Integer cod) {
        this.cod = cod;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Integer getMonto() {
        return this.monto;
    }
    
    public void setMonto(Integer monto) {
        this.monto = monto;
    }




}


